# Generated by Django 2.2.4 on 2019-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190920_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='date',
            new_name='dateOfReading',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='tank',
            new_name='leftSensorTemperature',
        ),
        migrations.AddField(
            model_name='temperature',
            name='middleSensorTemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='rightSensorTemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='tankSensorTemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
