# Generated by Django 2.2.4 on 2019-09-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190920_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='dateOfReading',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='leftSensorTemperature',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='middleSensorTemperature',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='rightSensorTemperature',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='tankSensorTemperature',
            new_name='t',
        ),
    ]
