# Generated by Django 2.2.4 on 2019-09-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190920_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='d',
            new_name='dateOfReading',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='l',
            new_name='leftSensorTemperature',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='m',
            new_name='middleSensorTemperature',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='r',
            new_name='rightSensorTemperature',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='t',
            new_name='tankSensorTemperature',
        ),
    ]
